services:
  afriqconsultingweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2724:8000  # Map the local port 2724 to the container port 8000
    volumes:
      - .:/afriqconsulting/  # Mount the entire project directory
      - static_volume:/afriqconsulting/static  # Persistent storage for static files
      - media_volume:/afriqconsulting/media  # Persistent storage for media files
      - logs_volume:/afriqconsulting/static/logs  # Mount logs volume
      - ./db.sqlite3:/afriqconsulting/db.sqlite3  # Explicitly mount the SQLite database file
    env_file:
      - ./.env
    restart: always

networks:
  aq_default:
    external: true

volumes:
  static_volume:
  media_volume:
  logs_volume:  # Add a new volume for logs