networks:
  acnetwork:
    driver: bridge
  proxy:
    external: true

volumes:
  static_volume:
  staticfiles_volume:
  media_volume:
  logs_volume:

services:
  afriqconsultingweb:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn afriqconsulting.wsgi:application
      --bind 0.0.0.0:8000
      --workers 2 --threads 2
      --timeout 60
      --log-level warning
    env_file: [.env]
    volumes:
      - .:/afriqconsulting
      - static_volume:/afriqconsulting/static
      - staticfiles_volume:/afriqconsulting/staticfiles
      - media_volume:/afriqconsulting/media
      - logs_volume:/afriqconsulting/logs
      # ⚠️ Dev/démo uniquement
      - ./db.sqlite3:/afriqconsulting/db.sqlite3
    restart: unless-stopped
    networks: [acnetwork, proxy]
    healthcheck:
      # évite curl si non présent
      test: ["CMD-SHELL", "python - <<'PY'\nimport urllib.request,sys\ntry:\n  urllib.request.urlopen('http://127.0.0.1:8000/healthz', timeout=2)\n  sys.exit(0)\nexcept Exception:\n  sys.exit(1)\nPY"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 40s
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      # Router HTTPS (apex)
      - traefik.http.routers.afriq.rule=Host(`afriqconsulting.com`)
      - traefik.http.routers.afriq.entrypoints=websecure
      - traefik.http.routers.afriq.tls.certresolver=lets

      # Service → port interne
      - traefik.http.services.afriq.loadbalancer.server.port=8000
      - traefik.http.services.afriq.loadbalancer.server.scheme=http

      # Middlewares (utilise ceux déjà déclarés côté Traefik, comme pour smitci)
      - traefik.http.routers.afriq.middlewares=sec-headers@docker,compress@docker,ratelimit@docker

      # (Optionnel) Router HTTP pour rediriger en HTTPS
      - traefik.http.routers.afriq-http.rule=Host(`afriqconsulting.com`,`www.afriqconsulting.com`)
      - traefik.http.routers.afriq-http.entrypoints=web
      - traefik.http.routers.afriq-http.middlewares=redir-https
      - traefik.http.middlewares.redir-https.redirectscheme.scheme=https

      # (Optionnel) Router HTTPS pour www
      - traefik.http.routers.afriq-www.rule=Host(`www.afriqconsulting.com`)
      - traefik.http.routers.afriq-www.entrypoints=websecure
      - traefik.http.routers.afriq-www.tls.certresolver=lets
      - traefik.http.routers.afriq-www.service=afriq
      - traefik.http.routers.afriq-www.middlewares=sec-headers@docker,compress@docker,ratelimit@docker