services:
  afriqconsultingweb:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/afriqconsulting/
      - static_volume:/afriqconsulting/static
      - staticfiles_volume:/afriqconsulting/staticfiles
      - media_volume:/afriqconsulting/media
      - logs_volume:/afriqconsulting/logs
      # ⚠️ En prod, éviter sqlite. Si tu restes dessus, garde le bind-mount :
      - ./db.sqlite3:/afriqconsulting/db.sqlite3
    env_file:
      - ./.env
    restart: always
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # === HTTPS (apex) ===
      - "traefik.http.routers.afriqweb.rule=Host(`afriqconsulting.com`)"
      - "traefik.http.routers.afriqweb.entrypoints=websecure"
      - "traefik.http.routers.afriqweb.tls.certresolver=lets"
      - "traefik.http.routers.afriqweb.service=afriqweb"

      # === HTTPS (www) → même service ===
#      - "traefik.http.routers.afriqweb-www.rule=Host(`www.afriqconsulting.com`)"
#      - "traefik.http.routers.afriqweb-www.entrypoints=websecure"
#      - "traefik.http.routers.afriqweb-www.tls=true"
#      - "traefik.http.routers.afriqweb-www.tls.certresolver=lets"
#      - "traefik.http.routers.afriqweb-www.service=afriqweb"

      # === Service (port interne) ===
      - "traefik.http.services.afriqweb.loadbalancer.server.port=8000"
      - "traefik.http.routers.afriqweb.middlewares=sec-headers@docker,compress@docker,ratelimit@docker"


      # === Middlewares (compression + headers sécurité) ===
#      - "traefik.http.routers.afriqweb.middlewares=afriqweb-compress,afriqweb-sec"
#      - "traefik.http.routers.afriqweb-www.middlewares=afriqweb-compress,afriqweb-sec"
#      - "traefik.http.middlewares.afriqweb-compress.compress=true"
#      - "traefik.http.middlewares.afriqweb-sec.headers.stsSeconds=31536000"
#      - "traefik.http.middlewares.afriqweb-sec.headers.stsIncludeSubdomains=true"
#      - "traefik.http.middlewares.afriqweb-sec.headers.stsPreload=true"
#      - "traefik.http.middlewares.afriqweb-sec.headers.contentTypeNosniff=true"
#      - "traefik.http.middlewares.afriqweb-sec.headers.referrerPolicy=no-referrer-when-downgrade"

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    driver: bridge
  proxy:
    external: true

volumes:
  static_volume:
  staticfiles_volume:
  media_volume:
  logs_volume: