# Generated by Django 4.2.16 on 2024-10-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
