# Generated by Django 4.2.16 on 2024-10-24 19:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0006_contactmessage_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NosServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhome.category')),
            ],
        ),
    ]
