# Generated by Django 4.2.16 on 2024-10-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0007_nosservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosservices',
            name='animclas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
